#
#
#

#SOURCES=profilGen.c
#OBJECTS=$(SOURCES:.c=.o)
LDFLAGS = -lm

# Compiler :
CC = gcc

# Options de compilation :
#CFLAGS = -g -Wall -ansi
CFLAGS = -O3 -Wall -ansi

#%.c: $*.h $*.c
#	gcc -o $* $*.c


clean :
	rm -f ./*.o
	rm -f ./*~

